### ISSUE TITLE
不能编译问题

### ISSUE THREAD

**Issue by suhanyujie** [netcan/AnimalChess#1]
你好~
        在 OSX 系统中，按照 readme 所说，先 clone 再 `cargo run --release`，过程中报错了：

```
note: ld: library not found for -lSDL2_image
```

**Comment by suhanyujie** [comment]
通过 `brew install sdl2 sdl2_image` 安装依赖库后，并将路径写入环境变量：

```
# vi ~/.bash_profile
export LIBRARY_PATH="/usr/local/lib"
source ~/.bash_profile
```

即可 `cargo run --release` 成功

**Comment by netcan** [comment]
好的多谢补充。
