### ISSUE TITLE
求教如何隐藏cmd命令窗口？

### ISSUE THREAD

**Issue by AnkoGo123** [netcan/AnimalChess#5]
现在运行程序后在windows系统会有cmd的命令行窗口也显现出来，请问怎么打包才能让他没有这个窗口？我只想显示程序窗口，求指点，

**Comment by netcan** [comment]
https://github.com/netcan/AnimalChess/blob/master/bin/src/main.rs
加上属性试试
```rust
#![windows_subsystem = "windows"]
```

**Comment by AnkoGo123** [comment]
> https://github.com/netcan/AnimalChess/blob/master/bin/src/main.rs
> 加上属性试试
> 
> ```rust
> #![windows_subsystem = "windows"]
> ```

真的起作用，在main.rs的最顶部加上这句话就没cmd窗口显示出来了，通过您的热心帮助和漂亮的代码，我渐渐发觉了自己的无知。。。虽然我不熟悉甚至不了解rust，但是最近已经在努力学习，只是rust确实不是一两天甚至不是一两周就可以入手的语言，我更加希望了解其中的算法原理，以前觉得红黑树比较复杂，现在觉得，。。这个算法更加复杂一些，或者说原理更加难懂，我会持续关注你的博客和github动态，希望大佬不吝赐教

**Comment by AnkoGo123** [comment]
您的博客，我用github登录不上去，应该是配置没对

**Comment by netcan** [comment]
> 您的博客，我用github登录不上去，应该是配置没对

你是指评论系统么？那个暂时不重要

**Comment by AnkoGo123** [comment]
> > 您的博客，我用github登录不上去，应该是配置没对
> 
> 你是指评论系统么？那个暂时不重要

是的

**Comment by AnkoGo123** [comment]
兄弟，我最近在做这个项目，无奈rust编译器太艰难，希望老哥可以帮我转成js，有偿，请及时回复我，我比较急，我已经被rust编译器深深击败了，求老哥今天回复我



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月4日(周六) 晚上7:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [netcan/AnimalChess] 求教如何隐藏cmd命令窗口？ (#5)




  
您的博客，我用github登录不上去，应该是配置没对
  
你是指评论系统么？那个暂时不重要
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by netcan** [comment]
> 兄弟，我最近在做这个项目，无奈rust编译器太艰难，希望老哥可以帮我转成js，有偿，请及时回复我，我比较急，我已经被rust编译器深深击败了，求老哥今天回复我

抱歉，我没有多余的精力搞这个，你自己想办法吧。

**Comment by AnkoGo123** [comment]
啊哈哈😃，谢啦，我肝了好久，发现自己真的不大懂rust，深深地挫败感，非常感谢老哥的及时回复和热心指导，我这边尽力去弄



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月8日(周三) 下午3:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [netcan/AnimalChess] 求教如何隐藏cmd命令窗口？ (#5)




  
兄弟，我最近在做这个项目，无奈rust编译器太艰难，希望老哥可以帮我转成js，有偿，请及时回复我，我比较急，我已经被rust编译器深深击败了，求老哥今天回复我
  
抱歉，我没有多余的精力搞这个，你自己想办法吧。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
